### ISSUE TITLE
ImportError: No module named samlib

### ISSUE THREAD

**Issue by ghost** [sfdodge/mixsalnet#2]
ImportError: No module named samlib
how to solve it ? thanks

**Comment by ake020675** [comment]
same problem

**Comment by g578g** [comment]
I want to download the trained weight file: vgg16_weights.h5 and mlnet_salicon.h5. But I cannot download it...
Wourld you please email this file to me? thank u very much.My email is 1959980755@qq.com

**Comment by VinuAbraham** [comment]
import error: no module named samlib. How to solve this??

@sfdodge

**Comment by sfdodge** [comment]
Fixed. Sorry it was some legacy code.
